### PR TITLE
Jasmeen/update bom logo 727

### PR DESCRIPTION
**Pull request by KAUR1984**
Fixes the issue #727.

### CODE REVIEW

**Review by atteggiani — CHANGES_REQUESTED** [review]
The changes are fine, but the branch contains commits that are not part of this PR. 

Please clean the branch keeping only the commits that are relevant (I think only [618d924de40ec09c1d19bc1df4600b4c21259944](https://github.com/ACCESS-NRI/access-hive.org.au/pull/738/commits/618d924de40ec09c1d19bc1df4600b4c21259944))

**Comment by KAUR1984** [comment]
Thanks @atteggiani ! I haven't tweaked the history of branch commits. I did some pulls (from development and main) and pushes, and that's what it seems to be reflecting :)

**Comment by atteggiani** [comment]
> Thanks @atteggiani ! I haven't tweaked the history of branch commits. I did some pulls (from development and main) and pushes, and that's what it seems to be reflecting :)

I see, but the branch needs to be rebased to `development`.

**Comment by KAUR1984** [comment]
Thanks Davide! I really like the non-destructive way of handling commits - using `git merge`, would not use `git rebase` unless I absolutely have to. Very happy to discuss it a bit more in our discussion :)

**Comment by atteggiani** [comment]
> Thanks Davide! I really like the non-destructive way of handling commits - using `git merge`, would not use `git rebase` unless I absolutely have to. Very happy to discuss it a bit more in our discussion :) Happy to leave this PR open till then :)

I am not talking about the way (merge/rebase) to add commits from feature branches (like your `jasmeen/update-bom-logo-727` to the `development` branch. We've been using merge-commits for that and is completely fine.

The `jasmeen/update-bom-logo-727` is not up to date with `development`. 
This means that there are commits in `developments` that were added after `jasmeen/update-bom-logo-727` was created (the commits are not included in the history of `jasmeen/update-bom-logo-727`). 
In general, it is always better to rebase the feature branches with `development` before merging to it, so we avoid any conflicts and make sure we are on track with `development`. In this case we should rebase and not merge because we don't want an additional merge-commit to be created for commits that are already present inside `development`.

Hopefully this explanation made sense.
Please let me know if you need further clarification :)

**Pull request merged**
