### PR TITLE
Add setup requirements to training materials page

### LINKED ISSUE #755: TRAINING 2024: Include the setup requirements in the training tab
## Description
Following discussion with @paigem, populate the `training materials` section with the setup requirements (in the email).

## Why
To collate all training related stuff under one tab. 

## Close criteria
- [ ] Create a setup requirements sections under the training materials.

### PR DESCRIPTION
**Pull request by paigem**
## Description

Add Training Day setup requirements in markdown format

Closes #755 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue, e.g. dead links)
- [x] New link / content

## Checklist:

- [x] The new content is accessible and located in the appropriate section
- [x] My changes do not break navigation and do not generate new warnings
- [x] I have checked that the links are valid and point to the intended content
- [x] I have checked my code/text and corrected any misspellings
- [ ] I have chosen the correct tag for the level of [support provided](https://access-hive.org.au/#support)

When your pull request is ready please [request a review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review). 

Unless there is a specific person you want your PR to be reviewd by, please select the **WebOps team**: `ACCESS-NRI/WebOps`. This ensures the load for reviewing pull requests is shared equitably.

### CODE REVIEW

**Review by flicj191 — APPROVED** [review]
Looks good :)

**Comment by atteggiani** [comment]
Thank you @paigem! 

Added a commit with minor changes:
- Added links to projects
- Minor formatting changes

I did it myself for quickness. Please check if it makes sense and you are fine with it, otherwise you're more than welcome to just remove my commit! :)

**Comment by KAUR1984** [comment]
Looks Awesome! Thanks for your work on this @paigem!

**Comment by paigem** [comment]
Looks great, thanks @atteggiani! 😄

**Comment by atteggiani** [comment]
I'll rebase and merge.

**Pull request merged**
