### PR TITLE
Periodical merge

### PR DESCRIPTION
**Pull request by atteggiani**
Periodical merge of `development` into `main`.

### CODE REVIEW

**Review by flicj191 — APPROVED** [review]
Thanks!
not sure why it's out of date from `main` though but fine to update

**Comment by atteggiani** [comment]
> Thanks! not sure why it's out of date from `main` though but fine to update

What do you mean?

**Comment by flicj191** [comment]
> > Thanks! not sure why it's out of date from `main` though but fine to update
> 
> What do you mean?

just below the checks it just says the branch is out of date with main. just needs to be updated to merge

**Comment by atteggiani** [comment]
> > > Thanks! not sure why it's out of date from `main` though but fine to update
> > 
> > 
> > What do you mean?
> 
> just below the checks it just says the branch is out of date with main. just needs to be updated to merge

Yeah I see. 
I think that happens because there are commits in `main` which are not present in `development`, but there are no file changed. The only difference in the history (before the current `main` HEAD) seems to be the merge commit `63da5242d6d8d6d6cf2545d9904527644567c84d` related to #690:

```
$ git log development..main

commit 63da5242d6d8d6d6cf2545d9904527644567c84d (origin/main, origin/HEAD, main)
Merge: a6f1023 ed4e650
Author: Davide Marchegiani <davide.marchegiani@gmail.com>
Date:   Thu Jun 6 10:32:07 2024 +1000

Merge pull request #690 from ACCESS-NRI/development

Periodical merge
```

Not sure why this is happening, but I would not worry for now.

**Pull request merged**
