### PR TITLE
:pencil2: (#693): Fixed the copyright year to 2024

### PR DESCRIPTION
**Pull request by KAUR1984**
Fixes the issue #693 

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1208142789290962

### CODE REVIEW

**Review by atteggiani — APPROVED** [review]
Thank you Jasmeen. 

Looks good and I approved. 
Just a note: I think we discussed already adding a JS function that automatically gets the year for the copyright, so we don't have to change it every year. 
I think this needs to be carried out to avoid other similar problems appearing every year.

I am happy to merge this as it is currently, or instead wait until the JS function has been implemented. 

What do you think?

**Comment by atteggiani** [comment]
Branch has been rebased with `development`

**Comment by KAUR1984** [comment]
Thanks @atteggiani ! I agree with using a JS function for the copyright year. I will work on the other high priority issues for now, and will come back to this afterwards. :)

**Comment by atteggiani** [comment]
I will then merge it as it is, and create another issue to add the JS function. 
That issue can be worked on even after the workshop.

**Pull request merged**
